#!/bin/bash
#jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.38
#jupyter labextension install jupyter-matplotlib
jupyter nbextension      enable --py --sys-prefix appmode
jupyter serverextension  enable --py --sys-prefix appmode
jupyter nbextension      enable --py widgetsnbextension
#python -m gnuplot_kernel install --user
#make
#git clone https://github.com/osscar-org/widget-code-input.git
#cd widget-code-input
#pip install -e .
#jupyter nbextension install --py --symlink --sys-prefix widget_code_input
#jupyter nbextension enable --py --sys-prefix widget_code_input

jupyter nbextension install --py --symlink --sys-prefix nglview
jupyter nbextension enable --py --sys-prefix nglview

git clone https://github.com/dou-du/jmolwidgets.git
cd  jmolwidgets
jlpm
jlpm run Build
jupyter labextension install .
pip install -e .
jupyter nbextension install --py --symlink --sys-prefix jmolwidgets
jupyter nbextension enable --py --sys-prefix jmolwidgets
